max_epochs: 400
max_steps: -1
gradient_accumulation_steps: 1
validation_interval: 2
max_patience: 5
save_max_score: false
chkpt_interval: 2
ckpt_dir: checkpoints
resume_from: null
step_on_batch: false

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.90
  patience: 3
  threshold_mode: rel
  cooldown: 2
  min_lr: 1e-6
