exp_name: default
mode: train

defaults:
  - trainer: default
  - logger: mlflow
  - model: unet # configs/model/unet.yaml
  - evaluator: default
  - _self_

# TODO: dataset conf
dataset:
  _target_: data.datasets.dataset.NonExistentDataset
  manifest_dir: data/manifests/hradis
  batch_size: 16
  num_workers: 4

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  weight_decay: 1e-4

loss:
  _target_: torch.nn.CrossEntropyLoss
