exp_name: ycbcr
run_name: validate_huber
eval_metric_prefix: real

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${exp_name}_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

load_ckpt: True

defaults:
  - evaluator: default
  - model: trmisr
  - logger: mlflow
  - _self_

model:
  _target_: models.trmisr.TransformerMISR_DoubleConvDecoder
  in_channels: 3

dataset:
  _target_: data.datasets.dataset.MISRDataset
  manifest_path: /pub/users/xnguye28/knn-sr/data/manifests/synth/test_manifest.json
  color_mode: ycbcr
  num_lr_images: 10
  samples_per_scene: 1
  hq_size:
    - 256
    - 256
  scale_factor: 4
  alignment_corruption_coeff: 0
  alignment_corruption_p: 0

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  num_workers: 0
  pin_memory: true

checkpoint_path: "/pub/users/xnguye28/knn-sr/outputs/finetune_colors_doubleconv_2026-05-09_20-45-43/checkpoints/best"
  
