exp_name: train
run_name: unet_real_ds

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${exp_name}_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

defaults:
  - trainer: default # loads key/value.yaml -> trainer/default.yaml
  - logger: unet
  - model: subpixel
  - _self_ # options from this file

train_dataset:
  _target_: data.datasets.dataset.MISRDataset
  manifest_path: /pub/users/xnguye28/knn-sr/data/manifests/hradis/pruned_train.json

val_dataset:
  _target_: data.datasets.dataset.MISRDataset
  manifest_path: /pub/users/xnguye28/knn-sr/data/manifests/hradis/pruned_val.json

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  num_workers: 4
  shuffle: true
  pin_memory: true

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3

loss:
  _target_: torch.nn.MSELoss
